-- Define overrides when playing on Hard

-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NGame.GREAT_POWER_FRENZY_QUICKSTART = 1
NDefines.NAI.POWERBALANCE_DISABLE_VERSUS_PLAYER = 0
NDefines.NAI.GREAT_POWER_ACTIONS_DISABLE_VERSUS_PLAYER = 0
NDefines.NAI.AGGRESSIVENESS = 400
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 400
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 200
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_MILITARY_RULERS = 0
NDefines.NAI.PEACE_DESPERATION_FACTOR = 30
NDefines.NAI.PEACE_WAR_EXHAUSTION_FACTOR = 0.8
NDefines.NAI.PEACE_MILITARY_STRENGTH_FACTOR = 15